version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1606_AWSTestProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
