version: "1.0"
projectName: Kvv_1606_AWSTestProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: testWorkflow
    type: workflow
    uid: fl969d4bd545844f67b740bd823a1e0135
    stepId: a0
    reference: services:add3Ints
  - name: testWorkflow
    type: workflow
    uid: fl969d4bd545844f67b740bd823a1e0135
    stepId: a2
    reference: project.kvv_1606_awstest.integrations:deepclonetest
- runtimeAlias: kvv_1606_AWSTest
  assets:
  - name: fld_111748608_stage00.projects.fl46901762d7ce4537beccb4fc75471c1a.integrations:tppfcs
    type: flow
    stepId: /0
    reference: fld_111748608_stage00.projects.fl46901762d7ce4537beccb4fc75471c1a.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
  - name: fld_111748608_stage00.projects.fl46901762d7ce4537beccb4fc75471c1a.integrations:tppfcs
    type: flow
    stepId: /1
    reference: fld_111748608_stage00.projects.fl46901762d7ce4537beccb4fc75471c1a.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: testWorkflow
    type: workflow
    uid: fl969d4bd545844f67b740bd823a1e0135
    stepId: a1
    reference: services:add3Ints
  - name: testWorkflow
    type: workflow
    uid: fl969d4bd545844f67b740bd823a1e0135
    stepId: a3
    reference: project.kvv_1606_awstest.integrations:deepclonetest
